-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 11:40:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`viaje` (
  `idviaje` INT NOT NULL,
  `horaInicio` DATETIME NULL,
  `horaFin` DATETIME NULL,
  `velocidadMedia` INT NULL,
  PRIMARY KEY (`idviaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instante` (
  `idinstante` INT NOT NULL,
  `hora` DATETIME NULL,
  `latitud` FLOAT NULL,
  `longitud` FLOAT NULL,
  `velocidad` INT NULL,
  `viaje_idviaje` INT NOT NULL,
  PRIMARY KEY (`idinstante`, `viaje_idviaje`),
  INDEX `fk_instante_viaje_idx` (`viaje_idviaje` ASC) VISIBLE,
  CONSTRAINT `fk_instante_viaje`
    FOREIGN KEY (`viaje_idviaje`)
    REFERENCES `mydb`.`viaje` (`idviaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
